plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.8'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'confeti'
version = '0.0.1-SNAPSHOT'
description = 'confeti-batch-server'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

ext {
    set('awspringVersion', '3.3.1')
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // Spring Batch Core
    implementation 'org.springframework.boot:spring-boot-starter-batch'

    // Spring Batch Integration
    implementation 'org.springframework.batch:spring-batch-integration'

    // JPA
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    // JDBC
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'

    // MySQL Driver
    runtimeOnly 'com.mysql:mysql-connector-j'

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // Testing
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.batch:spring-batch-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // OpenFeign
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'
    implementation 'io.github.openfeign:feign-okhttp:11.10'
    implementation 'io.github.openfeign:feign-jackson:11.10'

    // actuator
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    // Secret Manager
    implementation "io.awspring.cloud:spring-cloud-aws-starter-secrets-manager:${awspringVersion}"
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:2025.0.0"
    }
}

tasks.named('test') {
    useJUnitPlatform()
}
