spring:
  config:
    import:
      - classpath:common/application-common.yml
      - aws-secretsmanager:/confeti-api/prod/database?prefix=db-secrets.
      - aws-secretsmanager:/confeti-api/prod/notification?prefix=notification-secrets.

  application:
    name: confeti-batch-prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db-secrets.host}:${db-secrets.port}/${db-secrets.dbname}?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useLegacyDatetimeCode=false&rewriteBatchedStatements=true&sessionVariables=time_zone='Asia/Seoul'
    username: ${db-secrets.username}
    password: ${db-secrets.password}
    hikari:
      maximum-pool-size: 20

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    properties:
      hibernate.default_batch_fetch_size: ${chunkSize:100}

  batch:
    job:
      names: ${job.name:NONE}
      enabled: false # disable auto start when application run
    jdbc:
      initialize-schema: never
      schema: classpath:org/springframework/batch/core/schema-mysql.sql

  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB

logging:
  level:
    root: INFO # default
    org.sopt.confeti: INFO
    org.springframework.web: INFO
    org.springframework.batch: INFO

---
server:
  port: 8081

spring:
  config:
    activate:
      on-profile: blue
---
server:
  port: 8082

spring:
  config:
    activate:
      on-profile: green
